---
- name: Ensure non-free Debian repository is enabled
  apt_repository:
    repo: deb {{ steamcmd_deb_mirror }} {{ ansible_distribution_release }} {{ steamcmd_repositories }}
    state: present
  when:
    - ansible_os_family == "Debian"
    - not steamcmd_manual
  register: update_apt

- name: Ensure architecture i386 is enabled
  command: dpkg --add-architecture i386
  when:
    - not steamcmd_manual
    - ansible_os_family == "Debian"
    - ansible_userspace_architecture == "x86_64"
  register: update_apt

- name: Update package list
  apt:
    update_cache: yes
  when:
    - not steamcmd_manual
    - ansible_os_family == "Debian"
    - update_apt is defined
    - update_apt.changed

- debconf:
    name: steamcmd
    question: steam/question
    value: 'I AGREE'
    vtype: select
  when:
    - not steamcmd_manual
    - ansible_os_family == "Debian"

- debconf:
    name: steamcmd
    question: steam/license
    value: ''
    vtype: note
  when:
    - not steamcmd_manual
    - ansible_os_family == "Debian"

- name: Ensure steamcmd directory is installed
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ steamcmd_lib_path }}"
    - "{{ steamcmd_bin_path }}"
  when:
    - steamcmd_manual

- name: Ensure required packages are installed
  package:
    name: "{{ steamcmd_required_packages }}"
    state: present

- name: Ensure steamcmd is installed
  package:
    name: "{{ steamcmd_package }}"
    state: present
  when:
    - not steamcmd_manual

- name: Download SteamCMD for Linux
  get_url:
    url: "{{ steamcmd_download_url }}"
    dest: '/tmp/steamcmd_linux.tar.gz'
    force: yes
  when:
    - steamcmd_manual

- name: Extract SteamCMD
  unarchive:
    src: '/tmp/steamcmd_linux.tar.gz'
    dest: "{{ steamcmd_lib_path }}"
    copy: no
  when:
    - steamcmd_manual

- name: Setup SteamCMD bin symlink
  file:
    path: "{{ steamcmd_bin_path }}/steamcmd"
    src: "{{ steamcmd_lib_path }}/linux32/steamcmd"
    state: link
    force: yes
  when:
    - steamcmd_manual
