---
- include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Ensure steam user exists
  user:
    name: "{{ steamcmd_user }}"

- include: install.yml
